zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181"
kafka:
  image: wurstmeister/kafka:0.8.2
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    BROKER_ID: 1
    HOST_IP: 192.168.59.103
    PORT: 9092
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock